import { v4 as uuid } from "uuid";
import { Sticker, Tees, Bag, Hat } from "../../assets";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Don't Stop ",
    desc: "Motivation Stikers",
    price: "4",
    prev_price: "8",
    discount: "50",
    category: "Sticker",
    img: Sticker,
  },
  {
    _id: uuid(),
    title: "Cool Hat",
    desc: "black Devloper Hat",
    price: "40",
    prev_price: "80",
    discount: "50",
    category: "hat",
    img: Hat,
  },
  {
    _id: uuid(),
    title: "Printed Tees ",
    desc: "Motivation Stikers",
    price: "80",
    prev_price: "160",
    discount: "50",
    category: "Tees",
    img: Tees,
  },
  {
    _id: uuid(),
    title: "Github  Sticker ",
    desc: "Cat Github Sticker",
    price: "6",
    prev_price: "12",
    discount: "50",
    category: "sticker",
    img: Sticker,
  },
  {
    _id: uuid(),
    title: "Dev Bag ",
    desc: "Black Bag Leather",
    price: "6",
    prev_price: "12",
    discount: "50",
    category: "bag",
    img: Bag,
  },
  {
    _id: uuid(),
    title: "Keep Coding ",
    desc: "Coding Stikers",
    price: "3",
    prev_price: "6",
    discount: "50",
    category: "Sticker",
    img: Sticker,
  },
  {
    _id: uuid(),
    title: "Black Smart Hat",
    desc: "black Devloper Hat",
    price: "20",
    prev_price: "40",
    discount: "50",
    category: "hat",
    img: Hat,
  },
  {
    _id: uuid(),
    title: "Printed White Tees  ",
    desc: "Black Tees",
    price: "60",
    prev_price: "120",
    discount: "50",
    category: "Tees",
    img: Tees,
  },
  {
    _id: uuid(),
    title: "Github  Sticker ",
    desc: "Cat Github Sticker",
    price: "6",
    prev_price: "12",
    discount: "50",
    category: "sticker",
    img: Sticker,
  },
  {
    _id: uuid(),
    title: "Dev Bag ",
    desc: "Black Bag Leather",
    price: "6",
    prev_price: "12",
    discount: "50",
    category: "bag",
    img: Bag,
  },
];
